sequenceDiagram
    participant Payer FSP
    participant Moja Switch
    participant ALS
    participant Orchestrator
    participant Redis
    participant TCP Relay
    participant Legacy Switch
    participant ATM

Note right of ATM: User selects <br> Moja Cashout <br> Enters amount and<br> MSISDN
ATM ->> Legacy Switch: Request for cash out

Legacy Switch ->> TCP Relay: Legacy Authorization Request
Note over TCP Relay: Convert to JSON <br> Field mapping

TCP Relay ->> Redis: Queue to be processed
Redis ->> Orchestrator: Pick up message
Note over Orchestrator, Redis: Duplicate checks <br> Create transaction and legacy fees <br> Map transaction to legacy key

Orchestrator ->> ALS: GET parties/MSISDN/<msisdn>
ALS -->> Orchestrator: 202 Accepted
ALS ->> Orchestrator: PUT parties/MSISDN/<msisdn> 
Orchestrator -->> ALS: 200 Ok
Note over Orchestrator: Update payer info
 
Orchestrator ->> Moja Switch: POST /transactionRequests
Moja Switch -->> Orchestrator: 202 Accepted
Moja Switch ->> Payer FSP : POST /transactionRequests
Payer FSP -->> Moja Switch: 202 Accepted

Note left of Payer FSP: Create transaction <br> Generate quote ID

Payer FSP ->> Moja Switch: PUT /transactionRequests/<ID> <br> transactionId = <tx ID>
Moja Switch -->> Payer FSP: 200 Ok
Moja Switch ->> Orchestrator: PUT /transactionRequests/<txReqId> <br> transactionId = <tx ID>
Orchestrator -->> Moja Switch: 200 Ok

Note over Orchestrator: Store transactionId

Payer FSP ->> Moja Switch: POST /quotes
Moja Switch -->> Payer FSP: 202 Accepted
Moja Switch ->> Orchestrator: POST /qoutes
Orchestrator -->> Moja Switch: 202 Accepted

Note over Orchestrator: Create quote <br> Generate condition <br> Calculate fees

Orchestrator ->> Moja Switch: PUT /qoutes
Moja Switch -->> Orchestrator: 200 Ok
Moja Switch ->> Payer FSP: PUT /quotes
Payer FSP -->> Moja Switch: 200 Ok

Payer FSP ->> Moja Switch: GET /authorizations/<transactionRequestId>
Moja Switch -->> Payer FSP: 202 Accepted
Moja Switch ->> Orchestrator: Get /authorizations/<transactionRequestId>

Orchestrator ->> Moja Switch: 202 Accepted

Note over Orchestrator: Find correct relay
Orchestrator ->> Redis: Queue to be processed
Redis ->> TCP Relay: Pick up message
Note over TCP Relay, Legacy Switch: Convert to <br> Legacy Authorization Response
TCP Relay ->> Legacy Switch: Legacy Authorization Response

Legacy Switch ->> ATM: Legacy Authorization Response
Note right of ATM: Display quote